# This workflow will build a Java project with Maven and deploy it to My Azure Resource

name: Build and Deploy to Azure

on:
  push:
    branches: [ master ]
    paths-ignore:   # No Re-deploy
    - README.md
    - LICENSE
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # checkout the repo
    - name: 'Checkout GitHub Action' 
      uses: actions/checkout@master

    # Azure login
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Unlock secret file
    - name: GitHub Action to unlock git-crypt secrets
      uses: sliteteam/github-action-git-crypt-unlock@1.1.0
      env: 
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

    - name: Delete git crypt directory
      run: sudo rm -rf .git/git-crypt

    # Java Environment    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # deploy web app using Azure credentials
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'chat-web'

    # Azure logout 
    - name: logout
      run: |
        az logout
