# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven & Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    # Unlock secret file
    - name: GitHub Action to unlock git-crypt secrets
      uses: sliteteam/github-action-git-crypt-unlock@1.1.0
      env:
        GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

    - name: Delete git crypt directory
      run: sudo rm -rf .git/git-crypt

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Deploy to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        port: ${{ secrets.VPS_PORT }}
        password: ${{ secrets.VPS_PASSWORD }}
        source: "./target/chat-0.0.1-SNAPSHOT.jar"
        target: "/app/chat/"
        strip_components: 2